git-lfs/gitobj

object_db.go
object_db_test.go

This pull request adds to the standard set of functions for opening objects, an untyped `Open()`, appropriate for callers who know the name, but not the type of the object they are opening.
##
/cc @git-lfs/core, @rubyist

object_db.go: introduce untyped Open()

---

backend.go
backend_test.go
errors/errors.go
errors/errors_test.go
file_storer.go
memory_storer.go
memory_storer_test.go
object_db.go
object_db_test.go
pack/delayed_object.go
pack/set.go
pack/storage.go
storage/backend.go
storage/decompressing_readcloser.go
storage/multi_storage.go
storage/storage.go
storer.go

Currently we have a storer abstraction, but it isn't exposed, making it hard to mock the disk in unit tests that use this module.  This series wraps both the existing storers and the pack piece in a storage abstraction that can be overridden and used elsewhere.  It also provides a consistent error type so that we can tell when an object is missing versus when there's some more serious error.
This series is marked RFC because while I think it should be done, I'm finalizing the use of it in git-lfs/git-lfs and I want to be sure that if I need to make any changes that I do it before this series merges.

Add a storage abstraction

---

object_db.go

When we open a new object using the object database, ensure that we use
a ReadCloser for the uncompressed object.  This ensures that we close
the file we've opened when reading loose objects so we don't run out of
file descriptors.
Note that we do use this code path for reading loose objects in some
cases because we hand it a ReadCloser which automatically decompresses
the object.

object_db: use ReadCloser for uncompressed objects

---

backend.go

Previously, `gitobj` didn't handle reading and writing from alternate repositories.  Teach it to do so by creating multiple storage backends for reading and continuing to write into our current repository.
Note that because we have no integration tests for this repository, there are no tests for this.  I have manually tested and confirmed that this series works where it did not before.

Handle alternates

---

backend.go

When we're done with a file, ensure we close it, in case an error occurs unexpectedly, and handle the error from a Scanner object if we get one.
Apparently, I forgot to actually squash these changes into #6 and pushed a new version that didn't contain all of the suggested changes, so here they are, as a separate PR.

backend: improve error handling

---

pack/set.go

When we look for packs to read, we look for a pack file, and then an index, and fail if either one is missing.  When Git looks for packs to read, it looks only for indices and then checks if the pack is present.
The Git approach handles the case when there is an extra pack that lacks an index, while our approach does not.  Consequently, we can get various errors (showing up so far only on Windows) when an index is missing.
If the index file cannot be read for any reason, simply skip the entire pack altogether and continue on.  This leaves us no more or less functional than Git in terms of discovering objects and makes our error handling more robust.

pack/set: ignore packs without indices

---

commit.go
commit_test.go
object_db_test.go

When Git wishes to continue one or more of a commit's extra headers on
more than a single line, it writes out the following:
```
parent: <SHA-1>
tree: <SHA-1>
...
gpgsig: -----BEGIN PGP SIGNATURE-----
<signature>
-----END PGP SIGNATURE-----
```
Our current parsing implementation does not handle this correctly, based
on a misunderstanding that one line is equivalent to one extra header,
and vice versa.
In fact, the situation presently is even more dire than not parsing the
'gpgsig' header incorrectly: we'll split the signature end ending line
into their own "headers" and in doing so trim off the leading
whitespace. In practice, this means that we can corrupt commits when
round-tripping them in many interesting ways \[1\].
To address the situation, we do two things:
1. Teach gitobj that …

commit.go: support multi-line header continuations

---

pack/set.go

Git inteprets any files with .pack extensions as packs.
For example, look at prepare_pack function in https://github.com/git/git/blob/master/packfile.c
We should use same rules for Git LFS to prevent problems with arbitrary pack names.

Search packs as Git does

---

object_db.go

When writing a blob, there are two places where we use temporary files. First, we use them when we write the blob itself. Second, we use them when we encode the buffer. In both of these cases, however, we failed to close the file after we were done with it, leading to file descriptor leaks until Go garbage-collected the items.
Close each of these files when we're done with them. Place the defer statements after the os.Remove statements, since defer statements are done in LIFO order and Windows will be happier if we don't try to remove a file we have open.
With this change, I don't see any of the lingering files I reported in the original issue; they're all routinely closed, and only the pack remains open.
Fixes git-lfs/git-lfs#3689
/cc @ttaylorr as contributor
/cc @larsxschneider as …

object_db: prevent FD leaks when writing blobs

---

backend.go
backend_nix.go
backend_test.go
backend_windows.go
object_db.go

gitobj already supports reading alternates from the alternates file in the repository, but not from the `GIT_ALTERNATE_OBJECT_DIRECTORIES` environment variable. This series introduces a way to pass in such an environment variable so that it can be parsed and alternate paths can be read.
The actual reading of the environment variable comes in with Git LFS itself, which passes it to these functions. This happens so that we can centralize the handling of environment variables in one location.
This is part of the fix for #14; the remainder will come into Git LFS after this is merged.

Alternate object directories

---

go.mod

Go 1.13 really wants a Go version declaration at the bottom of the file and will modify it when any go command is run if it isn't present.  Because we'd like our files to be tidy and not show up as modified when we build or run tests, add a Go version declaration for Go 1.11 (the oldest we support) at the bottom of the file.

go.mod: add Go version directive

---

pack/set.go

When we open a pack file, we use a glob pattern to find the pack files that are in our pack directory and then attempt to open them.  This works fine if our directory contains no characters that are special to the shell, but works poorly when we handle characters that are special in glob patterns, most notably the left square bracket.  In such a case, our pattern doesn't actually match anything, so we don't open any pack files.  Git LFS then complains about a missing object.
Escape all the characters which are special to the shell so that we can handle these paths properly.  Use character classes instead of backslashes because backslash escaping is not available on Windows.  For the same reason, punt on handling backslashes on Unix systems because there isn't a great way to handle them …

pack: escape characters before using them in glob patterns

---

commit.go
commit_test.go

It's technically possible for commit messages to contain arbitrary non-NUL bytes.  Our commit message parser uses a 64 KiB buffer to read lines, and if lines are too long, it will fail.  We've seen some cases where commit message lines are much longer due to historical accidents.
Let's raise the maximum buffer size to 1 MiB to accommodate these situations.  Let's also make it easier to track problems by returning a more helpful error message if the buffer size is exceeded.
Fixes git-lfs/git-lfs#4005
/cc @woopla as reporter

Allow parsing very long lines in commit messages

---

.github/workflows/ci.yml
.travis.yml
script/cibuild

We're already using GitHub Actions for the main Git LFS codebase, so let's switch here as well.  We introduce a script to running CI which is currently very simple but can be expanded in the future if need be.  We run entirely on Ubuntu because there's very little that's OS specific in this module, and we support the same versions of Go that Git LFS does.

Switch to GitHub Actions for CI

---

pack/index.go
pack/index_v1.go
pack/index_v2.go
pack/packfile.go
tree.go

Expanding on the introduction of the `maxHashSize` constant in 528473bb155f46fe058248cf7c25a672cbc07d29, we can use this in several other places as well for byte array initialization.

use max hash size constant for all SHA byte arrays

---

tree.go

On most Unix systems, the stat constants (S_IFMT and friends) that Git uses are the same: that is, the system values are the same ones that Git uses.  However, on zOS, this isn't the case, and the system constants are different.
Let's add a set of our constants that are used by Git to determine the type of an object that will be right on all platforms instead of using the system constants.  Note that the tests already cover this case; they'll just now pass on additional systems.
Fixes #24

tree: don't use system stat constants

---

tree.go
tree_test.go

The `Tree.Merge()` function should only use filenames as the keys of a tree object's entries, not filenames combined with file modes, which at present can result in duplicate file entries reported by `git fsck` as errors.
We therefore change to use only the entry's names as keys when merging new and existing tree entries together, and adjust the basic tree merge test such that it would fail without this change.
We also add an extra check to the subtree order merge test, just to bring the two merge tests into alignment.
/cc git-lfs/git-lfs#4796

use filenames only as keys when merging tree entries

---

tree.go
tree_test.go

Some callers may need to disambiguate between regular blob objects and those which represent symbolic links, so we add
an `IsLink()` method to the `TreeEntry` class that returns true when the object is a blob and a symlink, and false otherwise.
We also expand the test suite slightly to exercise this new method.

add method to test if tree entries are symbolic links

---

commit.go
commit_test.go

Git contains some multiline headers, including `gpgsig`, `gpgsig-sha256`, and `mergetag` headers.  These headers start with a normal line of data and then are continued after a newline by indentation with a single space, which is stripped when computing the body.
Our header parsing for commits could misparse these because we use `strings.Fields`, which strips leading space.  As a result, if the mergetag message contains a line starting with "tree " and then a non-hex character, we'd fail parsing since we'd attempt to parse it as a tree header.  Let's fix this by using `strings.Split` instead, which doesn't strip space and therefore won't try to misparse this.
The fake commit is synthesized from be122abe4bcd6d39b37892daae28c8bf5e4030fc in the Linux kernel repository. Identifying …

Mergetag parsing

---

.github/dependabot.yml
.github/workflows/ci.yml

We update our GitHub Actions CI workflow to use the latest supported Go versions and the latest versions of all Actions steps, and we schedule monthly checks by the GitHub Dependabot service of our workflows to ensure we continue using the latest versions of all Actions steps.
Thanks tp @jlosito for the suggestion to add Dependabot Actions checks in git-lfs/git-lfs#5228.

Upgrade CI workflow to latest Go and Actions versions and add monthly checks

---

README.md
SECURITY.md

We're no longer using Travis CI, so we remove its status badge and add one for GitHub Actions.
We also update our link to the Git LFS project's main primary documentation in the `git-lfs/git-lfs` repository to use that repository's current default branch name of `main`.

Update status badge and default branch name in security documentation

---

README.md

In commit c735fc7bf09ba9c2944b9026d25baf7e75186ae8 of PR #31 we updated the CI status badge in our `README.md` file to reflect the fact that we are now using GitHub Actions rather than Travis CI.
However, we didn't include a link target for the new badge, so we do that now.

Add link target to status badge

---

.github/workflows/ci.yml

As our official [policy](https://github.com/git-lfs/git-lfs/blob/a3829f486597702297737bb6677534cb5cd0bbc6/CONTRIBUTING.md#prerequisites) for the Git LFS project is to support the latest version of Go, we upgrade our CI workflow to version 1.21, which was recently released.
We also drop CI job runs (and therefore official support) for versions older than 1.20, as they are not supported by upstream Go.
Note that several older required CI jobs will not run for this PR, and the newer jobs should be marked as required after this PR is merged.

Update to Go 1.21

---

commit.go
commit_test.go

eg:
```
tree 2aedfd35087c75d17bdbaf4dd56069d44fc75b71
parent 75158117eb8efe60453f8c077527ac3530c81e38
author Credit Card Account <Credit Card Account> 1722305889 +0800
committer \346\244\260\346\235\215
<Credit Card Account> 1722305889 +0800
Credit Card Account
```

Fix decoding panic caused by wrong commit
